version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password1
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "3456:3000"
    depends_on:
      - db
